import Head from 'next/head'
import Image from 'next/image'
import styles from './src/styles/Home.module.css'

import App from './src/App'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avani-RS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <App />
      </main>

    </div>
  )
}
